### ISSUE TITLE
TypeError: a bytes-like object is required, not 'BinaryFile'`

### ISSUE THREAD

**Issue by SumeyyeSuslu** [luohancfd/tecplotReader#1]
Getting following error when tecFile.data is accessed

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-20-0f44e54919c5>](https://localhost:8080/#) in <module>()
----> 1 zone_data = tecFile.data[0]

3 frames
[/content/tecplotReader.py](https://localhost:8080/#) in __getattribute__(self, item)
    794         if item == 'data':
    795             if not self.dataLoaded:
--> 796                 self.load_data()
    797         return super().__getattribute__(item)
    798 

[/content/tecplotReader.py](https://localhost:8080/#) in load_data(self, on_demand)
    813             # this method consumes less memory since the data is load on the fly
    814             with BinaryFile(self.binaryFilePath, 'rb') as f:
--> 815                 self.data = read_all_data(f, self.header, self.zone_header)
    816         else:
    817             logger.info("Loading the whole file in memory will take a long time")

[/content/tecplotReader.py](https://localhost:8080/#) in read_all_data(byte_list, file_header, zone_header, start_byte)
    749     for izone in range(len(zone_header)):
    750         # read zone one by one
--> 751         r, zone_counter = read_zone_data(byte_list, [start_byte], file_header, zone_header, zone_counter)
    752         start_byte = r[0][RESERVED_KEY]['_EndByte_']
    753         zones_list.append(r[0])

[/content/tecplotReader.py](https://localhost:8080/#) in read_zone_data(byte_list, zone_markers, file_header, zone_header, zone_counter)
    714             connect = np.frombuffer(byte_list, dtype=internal_data['_VarDtype_'][name],
    715                             count=NumElements * FEMNumNode[zt],
--> 716                             offset=offset)
    717             offset = offset + NumElements * FEMNumNode[zt]
    718             end_byte = offset

TypeError: a bytes-like object is required, not 'BinaryFile'`

**Comment by luohancfd** [comment]
This repository is archived. Give the new repo at https://github.com/luohancfd/tecplotReade a try
